### ISSUE TITLE
Are u8 values meant to be excluded? 

### ISSUE THREAD

**Issue by issackelly** [alexjg/autosurgeon#2]
When I add a "u8"  to the struct, it immediately fails, because u8s are excluded from the automatic implementations.

When I add them, I can't compile. I think there's something about how single bytes are managed in rust that I don't yet understand. 

Test: https://github.com/alexjg/autosurgeon/pull/1

**Comment by bluebear94** [comment]
A `u8` implementation would cause a conflict for `Vec<u8>`, which could either be represented by a bytes object or as a list of uints.

**Comment by alexjg** [comment]
Yeah that's the reason I've excluded them for now. I'm considering taking an approach similar to https://docs.rs/minicbor/latest/minicbor/bytes/index.html for this. We would have `Bytes` newtype which you wrap arrays of `u8` in. Thoughts?
